export var SystemColors;
(function (SystemColors) {
    SystemColors["BLACK"] = "#000000";
    SystemColors["MAROON"] = "#800000";
    SystemColors["GREEN"] = "#008000";
    SystemColors["OLIVE"] = "#808000";
    SystemColors["NAVY"] = "#000080";
    SystemColors["PURPLE"] = "#800080";
    SystemColors["TEAL"] = "#008080";
    SystemColors["SILVER"] = "#c0c0c0";
    SystemColors["GREY"] = "#808080";
    SystemColors["RED"] = "#ff0000";
    SystemColors["LIME"] = "#00ff00";
    SystemColors["YELLOW"] = "#ffff00";
    SystemColors["BLUE"] = "#0000ff";
    SystemColors["FUCHSIA"] = "#ff00ff";
    SystemColors["AQUA"] = "#00ffff";
    SystemColors["WHITE"] = "#ffffff";
})(SystemColors || (SystemColors = {}));
export var DefaultColors;
(function (DefaultColors) {
    DefaultColors["GREEN"] = "#03fcd7";
    DefaultColors["RED"] = "#fc038c";
    DefaultColors["ORANGE"] = "#fc9803";
    DefaultColors["BLUE"] = "#03a9fc";
    DefaultColors["YELLOW"] = "#f5d36e";
    DefaultColors["PURPLE"] = "#a46ef5";
    DefaultColors["PINK"] = "#e889cf";
    DefaultColors["WHITE"] = "#ffffff";
    DefaultColors["GREY"] = "#c0c0c0";
})(DefaultColors || (DefaultColors = {}));
export var PaleColors;
(function (PaleColors) {
    PaleColors["GREEN"] = "#9be0cc";
    PaleColors["RED"] = "#e09bb4";
    PaleColors["ORANGE"] = "#e0ba9b";
    PaleColors["BLUE"] = "#86b5d9";
    PaleColors["YELLOW"] = "#e8ebb2";
    PaleColors["PURPLE"] = "#e2b9f0";
    PaleColors["PINK"] = "#f0bde3";
})(PaleColors || (PaleColors = {}));
export var VividColors;
(function (VividColors) {
    VividColors["GREEN"] = "#02c94e";
    VividColors["RED"] = "#c90202";
    VividColors["ORANGE"] = "#fca000";
    VividColors["BLUE"] = "#0043fc";
    VividColors["YELLOW"] = "#fceb00";
    VividColors["PURPLE"] = "#b000fc";
    VividColors["PINK"] = "#fc00d2";
})(VividColors || (VividColors = {}));
export var ModestyColors;
(function (ModestyColors) {
    ModestyColors["GREEN"] = "#88c425";
    ModestyColors["LIGHT_GREEN"] = "#bef202";
    ModestyColors["AQUA"] = "#28adb4";
    ModestyColors["AQUA_LIGHT"] = "#a1f1f1";
    ModestyColors["SALMON"] = "#f72e40";
})(ModestyColors || (ModestyColors = {}));
export var SunriseColors;
(function (SunriseColors) {
    SunriseColors["RED"] = "#f2285d";
    SunriseColors["DARK_ORANGE"] = "#f24342";
    SunriseColors["MID_ORAGE"] = "#f26127";
    SunriseColors["LIGHT_ORANGE"] = "#f28819";
    SunriseColors["YELLOW"] = "#e0aC17";
    SunriseColors["LIGHT_YELLOW"] = "#f6de52";
    SunriseColors["CREAM"] = "#decd6b";
})(SunriseColors || (SunriseColors = {}));
export var ColdColors;
(function (ColdColors) {
    ColdColors["OLIVE_DARK"] = "#5eaac1";
    ColdColors["MID_OLIVE"] = "#35b5b7";
    ColdColors["DARK_AQUA"] = "#52c9b7";
    ColdColors["MID_AQUA"] = "#51ccd1";
    ColdColors["LIGHT_AQUA"] = "#6ddbcc";
    ColdColors["MINT"] = "#83fcf0";
    ColdColors["LIGHT_MINT"] = "#b4fdf5";
})(ColdColors || (ColdColors = {}));
